app = "n8n-render-holy-bird-5929"
primary_region = "sin"  # Use 'sin' (Singapore) since 'bom' has no volume capacity

[build]
  image = "n8nio/n8n:latest"

[env]
  N8N_HOST = "0.0.0.0"
  N8N_PORT = "5678"
  N8N_PROTOCOL = "http"
  N8N_USER_FOLDER = "/home/node/.n8n"
  N8N_BASIC_AUTH_ACTIVE = "true"
  N8N_BASIC_AUTH_USER = "yourUsername"
  N8N_BASIC_AUTH_PASSWORD = "yourPassword"
  TZ = "Asia/Kolkata"
  NODE_ENV = "production"

[mounts]
  source = "n8n_data"
  destination = "/home/node/.n8n"

[[services]]
  internal_port = 5678
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
